//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroEdge.Grantmaker.Business.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MicroEdge.Grantmaker.Business.Properties.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The client&apos;s configuration file was not found on the GrantMaker server..
        /// </summary>
        internal static string CFS_ConfigNotFound {
            get {
                return ResourceManager.GetString("CFS_ConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid Validation Key was specified in the Payload..
        /// </summary>
        internal static string CFS_InvalidValidationKey {
            get {
                return ResourceManager.GetString("CFS_InvalidValidationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The CFS directory structure for this client does not exist..
        /// </summary>
        internal static string CFS_MissingCFSDirectory {
            get {
                return ResourceManager.GetString("CFS_MissingCFSDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload is missing the Validation Key..
        /// </summary>
        internal static string CFS_MissingCheckSum {
            get {
                return ResourceManager.GetString("CFS_MissingCheckSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload is missing the client&apos;s Serial Number..
        /// </summary>
        internal static string CFS_MissingSerialNumber {
            get {
                return ResourceManager.GetString("CFS_MissingSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not currently configured for the Internet Grants Application Manager..
        /// </summary>
        internal static string CFS_NotConfigured {
            get {
                return ResourceManager.GetString("CFS_NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The wrong Serial Number was specified in the Payload..
        /// </summary>
        internal static string CFS_WrongSerialNumber {
            get {
                return ResourceManager.GetString("CFS_WrongSerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The applicant&apos;s email address does not satisfy email construction requirements..
        /// </summary>
        internal static string CreateApplicant_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("CreateApplicant_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create an Applicant. The Applicant&apos;s Email or Password were not specified..
        /// </summary>
        internal static string CreateApplicant_MISSING_EMAIL_PASSWORD {
            get {
                return ResourceManager.GetString("CreateApplicant_MISSING_EMAIL_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid payload..
        /// </summary>
        internal static string InvalidPayload {
            get {
                return ResourceManager.GetString("InvalidPayload", resourceCulture);
            }
        }
    }
}
